databases:
  - name: wishway_DB
    databaseName: wishway_db
    user: sumisumi
    region: singapore

services:
  - type: web
    name: wishway_db
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: wishway_db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
